import type {Metadata} from "next";
import Link from "next/link";
export const metadata:Metadata={title:"Procurement & RFQs",description:"Corporate purchasing, repeat-order coordination, specification-based quotes and vendor onboarding inquiries for Cayman Islands organizations."};
const steps=[
  {id:"01",title:"Send your requirement",detail:"Share an RFQ, product list, sample or detailed specification. Include quantities and required delivery dates."},
  {id:"02",title:"Scope & feasibility",detail:"We review customization, minimum quantities, supplier availability, import considerations and delivery needs."},
  {id:"03",title:"Quote & approval",detail:"Receive a tailored quotation with agreed product specifications and pricing in Cayman Islands dollars (KYD)."},
  {id:"04",title:"Production coordination",detail:"Following approval and agreed payment terms, CRÈME coordinates production and relevant quality checks."},
  {id:"05",title:"Freight & handover",detail:"We coordinate the agreed freight route, provide status updates and arrange Cayman delivery or collection."},
];
export default function ProcurementPage(){return <>
  <section className="subhero shell enterprise-subhero"><p className="eyebrow">B2B PROCUREMENT / 04</p><h1>PROCUREMENT.<br/><em>WITHOUT THE GUESSWORK.</em></h1><p>Built for businesses that need clear specifications, reliable communication and an accountable partner for branded products and international sourcing.</p><div className="page-actions"><Link className="button button-dark" href="/quote">Submit an RFQ ↗</Link><Link href="/corporate" className="text-link">Corporate capabilities ↗</Link></div></section>
  <section className="section shell page-section"><div className="section-heading"><div><p className="eyebrow">01 / PURCHASING WORKFLOW</p><h2>TRANSPARENT<br/><em>FROM DAY ONE.</em></h2></div><p>No guesswork on scope. Every project is confirmed in writing before we commit to product, pricing or a delivery timeline.</p></div><div className="procurement-timeline">{steps.map(s=><div key={s.id} className="procurement-timeline-item"><span>{s.id}</span><h3>{s.title}</h3><p>{s.detail}</p></div>)}</div></section>
  <section className="procurement-dark"><div className="shell procurement-dark-inner"><div><p className="eyebrow">02 / WHAT BUYERS CAN EXPECT</p><h2>BUILT AROUND<br/><em>YOUR REQUIREMENTS.</em></h2></div><div className="procurement-points"><div><strong>SPECIFICATION-BASED QUOTES</strong><p>Product descriptions, decoration, quantities and assumptions documented clearly.</p></div><div><strong>KYD PRICING</strong><p>Quote totals in Cayman Islands dollars, identifying freight and applicable duties or additional charges.</p></div><div><strong>APPROVED PROOFS</strong><p>Artwork and production details confirmed before orders are released.</p></div><div><strong>REPEAT ORDERS</strong><p>Support for recurring items and standard business merchandise requirements.</p></div></div></div></section>
  <section className="section shell enterprise-dual procurement-qualification"><div><p className="eyebrow">03 / VENDOR ONBOARDING</p><h2>READY TO DISCUSS<br/><em>YOUR PROCESS.</em></h2><p>If your organization has supplier onboarding, invoicing, procurement or documentation requirements, tell us. We can review the required information and confirm which documentation is available.</p><p>Government procurement and institutional purchasing remain subject to their own qualification, tender and contracting rules. This page does not imply prequalification or an existing customer relationship.</p><Link href="/contact" className="button button-dark">Discuss vendor onboarding ↗</Link></div><div className="procurement-brief"><span className="eyebrow">RFQ CHECKLIST</span><h3>GOOD INFORMATION<br/>GETS BETTER RESULTS.</h3><ul><li>Product or technical specification</li><li>Quantity, variants and size breakdown</li><li>Branding, packaging and artwork</li><li>Target delivery date and location</li><li>Budget range or purchasing terms</li><li>Any compliance or document requirements</li></ul><Link href="/quote" className="text-link">Start a quotation ↗</Link></div></section>
  <section className="project-banner"><div className="shell project-banner-inner"><div><p className="eyebrow">LET'S GET SPECIFIC</p><h2>SEND YOUR<br/><em>NEXT RFQ.</em></h2></div><Link href="/quote" className="button button-dark">Request a quote ↗</Link></div></section>
</>}
