import type {Metadata} from "next";
import Link from "next/link";

export const metadata:Metadata={title:"Corporate Merchandise & Supply",description:"Custom corporate merchandise, staff uniforms, executive gifts and branded programs for Cayman Islands organizations."};
const solutions=[
  {no:"01",need:"uniforms",title:"Uniforms & workwear",desc:"Polos, shirts, jackets, safety wear and coordinated team apparel with consistent decoration."},
  {no:"02",need:"merchandise",title:"Corporate gifting",desc:"Presentation-ready employee gifts, branded drinkware, notebooks, bags and executive merchandise."},
  {no:"03",need:"merchandise",title:"Staff onboarding kits",desc:"Welcome packages, desk essentials and new-hire merchandise planned around your brand."},
  {no:"04",need:"merchandise",title:"Events & campaigns",desc:"Conference kits, event apparel, giveaways, signage-related merchandise and custom keepsakes."},
  {no:"05",need:"custom",title:"Custom packaging",desc:"Printed boxes, labels, presentation sleeves and product packaging matched to your specifications."},
  {no:"06",need:"repeat",title:"Ongoing supply",desc:"Repeat purchase requirements, approved specifications, reorders and consolidated product requests."}
];
const sectors=["Financial services", "Legal & professional services", "Government departments", "Hospitality & tourism", "Education & institutions", "Property & facilities", "Events & organizations", "Growing local businesses"];
export default function CorporatePage(){return <>
  <section className="subhero shell enterprise-subhero"><p className="eyebrow">CORPORATE SERVICES / 01</p><h1>MERCHANDISE<br/><em>MEANS BUSINESS.</em></h1><p>Elevated branded products and practical business supplies, managed through one local relationship with international production capability.</p><div className="page-actions"><Link className="button button-dark" href="/corporate/request">Start a corporate RFQ ↗</Link><Link className="text-link" href="/procurement">Procurement information ↗</Link></div></section>
  <section className="section shell page-section"><div className="section-heading"><div><p className="eyebrow">01 / OUR CORPORATE CAPABILITIES</p><h2>PRODUCTS THAT<br/><em>REPRESENT YOU.</em></h2></div><p>Whether outfitting a department, preparing an event or building a consistent merchandise program, we start with your standards and brief.</p></div>
  <div className="corporate-solutions">{solutions.map(s=><Link className="solution-row" href={`/corporate/request?need=${s.need}`} key={s.no}><span>{s.no}</span><div><h3>{s.title}</h3><p>{s.desc}</p></div><span className="solution-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
  <section className="business-audience"><div className="shell"><p className="eyebrow">02 / WHO WE BUILD FOR</p><h2>BUILT FOR TEAMS<br/><em>OF EVERY SIZE.</em></h2><p className="audience-caption">Examples of organizations we can serve, not a list of existing clients or endorsements.</p><div className="audience-grid">{sectors.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div></div></section>
  <section className="section shell enterprise-dual"><div><p className="eyebrow">03 / FOR PURCHASING TEAMS</p><h2>FROM THE FIRST RFQ<br/><em>TO THE NEXT REORDER.</em></h2><p>Provide detailed specifications or a product reference. We can evaluate suitable options, itemize pricing in KYD and coordinate a clear approval process before manufacturing begins.</p><p>Vendor information and capability details can be supplied as part of an onboarding discussion. We do not claim approved-vendor status with any institution.</p><Link className="button button-dark" href="/corporate/request">Send your purchasing brief ↗</Link></div><div className="document-visual" aria-label="Illustration of an itemized quotation"><span>CRÈME / CORPORATE</span><h3>PRODUCT<br/>SPECIFICATION</h3><div className="document-line"><span>ITEM</span><span>QTY</span></div><div className="document-line"><span>EMBROIDERED POLOS</span><span>150</span></div><div className="document-line"><span>CUSTOM PACKAGING</span><span>150</span></div><div className="document-line"><span>DELIVERY</span><span>CAYMAN</span></div><strong>QUOTE REQUEST / EXAMPLE</strong></div></section>
  <section className="project-banner"><div className="shell project-banner-inner"><div><p className="eyebrow">TELL US WHAT YOUR ORGANIZATION NEEDS</p><h2>LET'S MAKE<br/><em>BUSINESS EASIER.</em></h2></div><Link href="/corporate/request" className="button button-dark">Start an RFQ ↗</Link></div></section>
</>}
