import type {Metadata} from "next";
import Link from "next/link";
import {SourcingForm} from "./sourcing-form";

export const metadata:Metadata={title:"Global Product Sourcing",description:"Ask CRÈME to assess custom and bulk product sourcing through overseas supplier networks, coordinated for Cayman Islands delivery."};
const groups=[
  {label:"01 / OFFICE & CORPORATE",title:"Workspace essentials",description:"Desk accessories, stationery, folders, organizers, onboarding items and custom corporate gift sets."},
  {label:"02 / BRANDED & PROMOTIONAL",title:"Merchandise for moments",description:"Custom drinkware, tech accessories, tote bags, event gifts, awards and presentation kits."},
  {label:"03 / APPAREL & UNIFORMS",title:"Teams that look the part",description:"Uniform programs, headwear, staff apparel, specialty fabrics, trims and branded accessories."},
  {label:"04 / PRESENTATION & PACKAGING",title:"Finishing details",description:"Rigid boxes, labels, bags, printed packaging, protective cases and purpose-made product displays."},
  {label:"05 / HOSPITALITY & FACILITIES",title:"Products for operations",description:"Select guest products, branded service items, storage goods and commercial-use accessories."},
  {label:"06 / SOMETHING ELSE",title:"Bring us the challenge",description:"Have a sample, specification sheet or product link? Tell us what you need and we'll assess viable options."}
];
export default function SourcingPage(){return <>
  <section className="subhero shell enterprise-subhero"><p className="eyebrow">GLOBAL SOURCING / 03</p><h1>NEED IT?<br/><em>LET'S FIND A WAY.</em></h1><p>One point of contact for custom and bulk product sourcing. Share what you're looking for, and CRÈME can review available manufacturing options, costs and delivery requirements.</p><div className="page-actions"><Link href="#sourcing-inquiry" className="button button-dark">Submit a sourcing inquiry ↗</Link><Link href="/procurement" className="text-link">How purchasing works ↗</Link></div></section>
  <section className="source-band"><div className="shell"><span>YOUR REQUIREMENT</span><span aria-hidden="true">→</span><span>SUPPLIER OPTIONS</span><span aria-hidden="true">→</span><span>APPROVED PRODUCTION</span><span aria-hidden="true">→</span><span>CAYMAN DELIVERY PLAN</span></div></section>
  <section className="section shell page-section"><div className="section-heading"><div><p className="eyebrow">01 / WHAT WE CAN EXPLORE</p><h2>MORE POSSIBILITIES.<br/><em>ONE CONTACT.</em></h2></div><p>Use these as starting points, not a guaranteed inventory catalog. Product feasibility, legal requirements, minimum orders and availability vary.</p></div><div className="source-category-grid">{groups.map(g=><div className="source-category" key={g.label}><span className="eyebrow">{g.label}</span><h3>{g.title}</h3><p>{g.description}</p></div>)}</div></section>
  <section className="sourcing-caveat"><div className="shell sourcing-caveat-inner"><p className="eyebrow">A PROFESSIONAL PROMISE</p><h2>WE'LL TELL YOU<br/><em>WHAT'S POSSIBLE.</em></h2><p>Not every product can be imported or sourced economically. We assess specifications, supplier reliability, minimum order quantities, quality needs and Cayman import requirements before confirming an order. No purchase or production commitment is made until both parties approve the terms.</p></div></section>
  <section className="section shell sourcing-form-section" id="sourcing-inquiry"><div className="section-heading"><div><p className="eyebrow">02 / SOURCE A PRODUCT</p><h2>SHOW US<br/><em>WHAT YOU NEED.</em></h2></div><p>Tell us about the product and your requirements. This is a non-binding inquiry, not a purchase order.</p></div><div className="sourcing-form-grid"><aside className="sourcing-assist"><h3>WHAT HELPS US QUOTE.</h3><p>A photo link, product page or specification sheet is a great starting point. Include a realistic quantity and your target landed budget in Cayman dollars, if known.</p><div className="quote-tips"><span>PRODUCT DESCRIPTION</span><span>QUANTITY & DIMENSIONS</span><span>BRANDING OR CUSTOMIZATION</span><span>TARGET BUDGET (KYD)</span><span>DELIVERY LOCATION & DATE</span></div><p>Looking for corporate apparel instead? <Link href="/quote?service=Corporate%20merchandise">Request a corporate quote ↗</Link></p></aside><SourcingForm/></div></section>
</>}
